### ISSUE TITLE
[Bug][4.0.6]ArgumentNullException occurs for records in .Net 7.0

### ISSUE THREAD

**Issue by ibs-ts** [thomasgalliker/ObjectDumper#109] opened 2023-06-16 05:59 UTC
### Description

I tried to update to the latest nuget version, but it seems there is an issue with your record handling.

### Steps to Reproduce

1.  Create a new C# console application with .NET 7.0 and add the nuget package with version 4.0.6
2. Execute the following code:

```using ObjectDumping;

var definition = new SampleData() { Name = "Test" };

var str = ObjectDumper.Dump(definition, new DumpOptions()
{
    IndentChar = '\t',
    IndentSize = 1,
    LineBreakChar = Environment.NewLine,
    DumpStyle = DumpStyle.CSharp
});

Console.WriteLine(str);

public readonly record struct SampleData
{
    public required string Name { get; init; }
}
```

3. Exception is thrown.

### Expected Behavior

Value of str:

> var sampleData = new SampleData
> {
> 	Name = "Test"
> };

### Actual Behavior

ArgumentNullException from ObjectDumperCSharp Line 68 (because 'recordCtor.Parameters' is null)

### Basic Information

- Version with issue: 4.0.6
- Last known good version: 3.5.6

**Comment by thomasgalliker** [comment] 2023-06-17 11:08
Thanks for reporting this issue. I'm looking at it right now. I will post a pre-release nuget package as soon as the fix is ready.

**Comment by thomasgalliker** [comment] 2023-06-17 11:15
The nuget pre-release that contains the bug fix for this issue is available here:
[https://www.nuget.org/packages/ObjectDumper.NET/4.1.1-pre](https://www.nuget.org/packages/ObjectDumper.NET/4.1.1-pre)

Can you @ibs-ts verify if the problem is solved and give feedback, please? I'll release a stable nuget version afterwards.

**Comment by ibs-ts** [comment] 2023-06-19 05:46
I've tested 4.1.1-pre with our rather complex model and at least the integration tests succeed. 
Thank you for the fix.
Of course it requires more testing and benchmarking after the stable version is released to find any issues.

**Comment by ibs-ts** [comment] 2023-06-19 06:08
Side note:

After writing the above comment, I had the idea to add a delegate property to the SampleData-class.
This results in a 'wall-of-text'-output. It's not part of this this issue, but I add this so you are aware:

```
var definition = new SampleData() { Name = "Test", Func = (param) => param };

var str = ObjectDumper.Dump(definition, new DumpOptions()
{
    IndentChar = '\t',
    IndentSize = 1,
    LineBreakChar = Environment.NewLine,
    DumpStyle = DumpStyle.CSharp
});

Console.WriteLine(str);

public readonly record struct SampleData
{
    public required string Name { get; init; }
    public Func<object, object> Func { get; init; }
}
```

Delegate/lambda/expression output might open pandoras box. I've tried this in the past with visitors. But as soon as you inject parameters (external or referenced) it causes headaches.

**Closed** 2023-06-20 07:20 UTC
Labels: bug
